variables:
  YARN_CACHE_FOLDER: &yarn_cache_path "$CI_PROJECT_DIR/.yarn_cache_pdf_wrap"

cache:
  key: "pdf_wrap_yarn_node_cache-$CI_COMMIT_REF_SLUG"
  paths:
    - *yarn_cache_path

before_script:
  - yarn install --frozen-lockfile --non-interactive --link-duplicates

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  timeout: "5m"
  script:
    - yarn gulp lint
  allow_failure: true
  image: node:lts-alpine

test:
  stage: test
  script: yarn gulp test
  tags:
    - node

build:
  stage: build
  script: yarn run gulp repackage
  tags:
    - node
  only:
    refs:
      - master
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
    - build/
    expire_in: 30 days

deploy:
  stage: deploy
  only:
    refs:
      - master
  script: npm publish build/distributions/npm --access public
  tags:
    - node
  when: manual
  dependencies:
    - build
  allow_failure: false

