cache:
  key: node
  paths:
    - node_modules

before_script:
  - yarn install --frozen-lockfile --non-interactive --link-duplicates

stages:
  - test

test:
  stage: test
  script: yarn gulp test
  tags:
    - node
