.node_docker:
  timeout: "10m"
  image: node:lts-alpine

.chromium_docker:
  timeout: "10m"
  variables:
    CHROME_BIN: "chromium-browser"
  image: zenika/alpine-chrome:83-with-node-12

variables:
  YARN_CACHE_FOLDER: &yarn_cache_path "$CI_PROJECT_DIR/.yarn_cache_pdf_wrap"

cache:
  key: "pdf_wrap_yarn_node_cache-$CI_COMMIT_REF_SLUG"
  paths:
    - *yarn_cache_path

before_script:
  - yarn install --frozen-lockfile --non-interactive --link-duplicates

stages:
  - lint
  - build
  - test
  - deploy

lint:
  stage: lint
  extends: .node_docker
  script: yarn workspace @srag/pdf-wrap run gulp lint

build:
  stage: build
  extends: .node_docker
  script: yarn workspace @srag/pdf-wrap run gulp repackage
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - pdf-wrap/lib
      - pdf-wrap/assets
    expire_in: 30 days

test:code:
  stage: test
  extends: .chromium_docker
  script: yarn workspace @srag/pdf-wrap run gulp test
test:deploy_dry_run:
  stage: test
  extends: .node_docker
  script:
    - npm publish pdf-wrap --dry-run --access public
  dependencies:
    - build
test:authorization:
  stage: test
  extends: .node_docker
  script:
    - npm whoami

deploy:
  stage: deploy
  extends: .node_docker
  only:
    - /^v\d+\.\d+\.\d+$/
  except:
    - branches
  script: npm publish pdf-wrap --access public
  when: manual
  dependencies:
    - build
  allow_failure: false

