site_name: PDF Wrap
site_description: "Full documentation of PDF Wrap. Includes guides, API documentation, reference documentation, development guide and examples."
site_author: "studer + raimann ag"
site_url: "https://studer-raimann.github.io/pdf-wrap"

copyright: "Creative Commons Attribution-ShareAlike 4.0 International License"

pages:
  - Home: index.md
  - Guides:
    - 'Basic PDF viewer': guides/basic-viewer.md
  - Reference Documentation: reference-documentation.md
  - Development Guide: development-guide.md

site_dir: "build/docs/mkdocs"

dev_addr: "localhost:8000"